#!/bin/zsh
#

zmodload zsh/mapfile zsh/mathfunc

readonly FileTemp=/tmp/ListeAppelsNonTaxa
CostId=1
Cost=0
CallLength=0

GetTaxaInfo () {
    # $1 numéro
    # $2 le champ à retourner
    sudo -u postgres psql -A -t asterisk -c "\
        SELECT ${2}
            FROM ${Chan}
            WHERE area @> '${1}'
            ORDER BY area
            ASC
            LIMIT 1;
    "
}

# On récupère la liste des comm non taxées
## -A avoir le format unaligned (ie Valeur1|Valeur2 et non Valeur1   |    Valeur2)
## -t ne pas afficher les en-têtes
## le ceil est là pour arrondir à la seconde supérieure
MaxId=$(sudo -u postgres psql -A -t asterisk -c "\
    SELECT MAX(id)
        FROM call_log;
    ")
sudo -u postgres psql -A -t asterisk -c "\
    SELECT id,destination_exten,destination_line_identity,CEIL(EXTRACT(EPOCH FROM duration)) AS duration
        FROM call_log
        WHERE valo IS null
            AND destination_exten LIKE '0%'
            AND answered = 't'
            AND source_exten NOT LIKE '0%'
            AND source_exten != 'anonymous';
    " > ${FileTemp}

FLINES=( ${(f)mapfile[${FileTemp}]} )
for ITEM in $FLINES
do
    Id=${ITEM[(ws:|:)1]}
    Dest=${ITEM[(ws:|:)2]:1}
    Chan=${ITEM[(ws:|:)3]:4}
    Duration=${ITEM[(ws:|:)4]}

    CallLength=${Duration}
    Cost=0
    CostId=1
    while [ ${CallLength} -ne 0 ] ; do
        if [ ${CallLength} -gt $(GetTaxaInfo ${Dest} duration${CostId}) ] ; then
            ValoLength=$(GetTaxaInfo ${Dest} duration${CostId})
        else
            ValoLength=${CallLength}
        fi

        # Calcul du coût
        Cost=$(($Cost+($(GetTaxaInfo ${Dest} cost${CostId})/$(GetTaxaInfo ${Dest} interval${CostId})*${ValoLength})))
        CallLength=$((${CallLength}-${ValoLength}))
        CostId=$((${CostId}+1))
    done
    sudo -u postgres psql -q -A -t asterisk -c "\
        UPDATE call_log
            SET valo = '${Cost}' WHERE id = '${Id}';
    "
done
# On marque comme traitée les taxa
sudo -u postgres psql -q -A -t asterisk -c "\
    UPDATE call_log
        SET stats = 1 WHERE id <= '${MaxId}';
"
